version: "3.3"

services:
  
  mongodb:
    container_name: database
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: testPWD123
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u mongoadmin -p testPWD123 --quiet | grep 1
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 3s
  
  backend:
    container_name: backend
    build:
      context: backend
    restart: unless-stopped
    ports: 
      - "5000:5000"
    build:
      context: backend
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: testPWD123

  frontend:
    container_name: frontend
    build: 
      context: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started